### ISSUE TITLE
npm dist-tag

### ISSUE THREAD

**Issue by scott113341** [rtsao/styletron#10]
```text
~|⇒ npm info styletron dist-tags
{ latest: '2.0.0-beta.0' }
```

Is this is what you want?  If so, feel free to `wontfix` `invalid`

[Related](https://github.com/npm/npm/issues/13248)

**Comment by rtsao** [comment]
Yeah, I thought about this but figured that folks doing `npm install styletron` at this point expect 2.x. Consumers of 1.x are typically using a wrapper with an explicit `styletron@1` dependency and they don't interact with it directly. Thanks for the heads up though!

**Comment by rtsao** [comment]
But I should probably just release `2.0.0`.
