### ISSUE TITLE
Missing vendor specific rules

### ISSUE THREAD

**Issue by andreiduca** [rtsao/styletron#103]
`-webkit-overflow-scrolling` is not treated as a valid ruled and it's not rendered. Same for `-ms-overflow-style`.

**Comment by rtsao** [comment]
Isn't `-webkit-overflow-scrolling` only implemented by Safari on iOS? In a Codepen it doesn't seem to be valid on Chrome 57 on Mac (with plain CSS, not using Styletron).

**Comment by andreiduca** [comment]
Yes, `-webkit-overflow-scrolling` is only for mobile (iOS) Safari: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling#compat-mobile and enables momentum scrolling https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/
And `-ms-overflow-style` is used to auto hide scrollbars in some IE browsers: https://css-tricks.com/snippets/css/hide-scrollbar-in-edge-ie-1011/

**Comment by rtsao** [comment]
Styletron just passes through declaration properties directly to the JavaScript [`CSSStyleSheet.insertRule()`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) API. So on those devices where those properties are valid, they should be injected correctly. However, on any other device they will not as `insertRule` will reject it.

**Comment by andreiduca** [comment]
Verified on an iPhone with Safari Web Inspector and the rule is there. Thanks for the explanation!
