### ISSUE TITLE
[RFC] Collapse vendor prefixes into single atomic class

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#104]
### What needs to be done?

Vendor prefixing needs to be rolled in to the core module, because it changes the implementation details of `injectDeclation`. It's possible this could be implemented as an alternate core module, so folks who don't want this don't have to use it.

### What are the benefits?

**Fewer classes**
- Nicer style inspection experience w/ DevTools out of the box
- Better theoretical performance
  - Fewer classes per element involved in style calculation
  - Shorter class strings (Fewer bytes over the wire)

**Possibly more robust SSR in the case of not shipping a static prefix map to the client.**
This is ~1.5 KB *gzipped* which is rather large in comparison to a Preact/lightweight app.

How does rolling up vendor prefixes into a single atom class make SSR in this case more robust? We can figure out at runtime which prefixes are required (for both values and properties). We can cache/memoize this too so there's only a startup cost. If we don't care about SSR, we can always do this. But if we care about SSR, ensuring our client-rendered markup is identical to the server-rendered markup can be difficult. We can guess based on user agent which prefixes are needed, but my thinking is this will never be 100% robust, and could lead to instances where extra/fewer atomic classes are produced in the client render than the server, leading to different markup. If vendor prefixes are rolled up into a single atomic class, then we can hydrate based on the original unprefixed declaration and ensure we never have different markup than the server render, as regardless of the resultant vendor prefixing, the same, single atomic class will be produced.

**Comment by rtsao** [comment]
Since https://github.com/rtsao/styletron/pull/127 was landed, there's no longer a requirement for this to be in the core! So now this can merely be a userland plugin.

**Comment by faddee** [comment]
We could make this work for `injectStylePrefixed` if we run `prefixAll` from `inline-style-prefixer` on each key and makes sure the whole returned object is injected using the new `injectRawDeclaration`. It won't be as "smart" as you describe it, but at least it's a step forward.
