### ISSUE TITLE
Collision with react-fontawesome

### ISSUE THREAD

**Issue by Ayc0** [rtsao/styletron#107]
As fontawesome uses the class fa, and as styletron can create a class named `.fa`, their is a collision.
This className should be reserved

**Comment by ZeeCoder** [comment]
This sounds like more of an issue with how unique the generated classes are in general.

Even if the "fa" class were reserved, this might happen again.

**Comment by Ayc0** [comment]
Could their be a param that could be set in the Provider which contains a list of forbidden classNames ?

**Comment by rtsao** [comment]
The default assumption with Styletron is there's no existing global CSS, but if you do have some global CSS, you can set a prefix to prevent collisions.

```
const styletron = new Styletron({
  prefix: '_'
});

// will yield `_fa` instead of `fa`
```

**Comment by Ayc0** [comment]
oh, I didn't know this
thanks a lot \o/

**Comment by Ayc0** [comment]
oh, I didn't know this
thanks a lot \o/
