### ISSUE TITLE
React.PropTypes 

### ISSUE THREAD

**Issue by joeshub** [rtsao/styletron#115]
React 15.5 wants PropTypes imported from "prop-types" now

**Comment by rtsao** [comment]
Thanks for reminding me. I'll run the codemod when I get a chance. Happy to accept a PR for this also 😄

**Comment by joeshub** [comment]
I tried the codemod on a project, it works for the most part but has some quirks. Definitely a good starting place. I noticed it is also great at finding bugs in my code

**Comment by rtsao** [comment]
Fixed in https://github.com/rtsao/styletron/pull/116
