### ISSUE TITLE
Multiple pseudo selectors

### ISSUE THREAD

**Issue by benjaminhadfield** [rtsao/styletron#121]
Hey, loving Styletron ❤️

Just wondering if there is a way to set multiple pseudo classes in a single key. Something like the following:
```
styled('a', {
  ':hover, :active': {
    color: 'red'
  }
})
```

**Comment by rtsao** [comment]
Glad you're liking it so far!

To answer your question, unfortunately not. While convenient, I think parsing every property to determine if it contains multiple psuedo selectors would have a nontrivial performance impact. I think this is a good case for a helper function. For example, something like this might work:

```js
const multi = (keys, style) =>
  Object.assign.apply(null, keys.map(key => ({[key]: style})))

const Anchor = styled('a', {
  ...multi([':hover', ':active'], {
    color: 'red'
  }
})
```

Or perhaps a higher-level abstraction might be nicer:

```js
const active = style => Object.assign({}, {':hover': style}, {':active': style})

const Anchor = styled('a', {
  ...active({
    color: 'red'
  }
})
```

**Comment by benjaminhadfield** [comment]
Ah, I see. Writing some helper function is a great idea, thanks!

**Comment by ecarrera** [comment]
@rtsao today exists a better implementation instead this? Do styletron supports scss?
