### ISSUE TITLE
Typescript - contextTypes 

### ISSUE THREAD

**Issue by sammkj** [rtsao/styletron#122]
I'm trying to use `context` but keep getting error:

```
// Here's what I'm trying to do
const MyComponent = styled("div", (_, context) => ({
  "color": context.theme.color,
}));

MyComponent.contextTypes = {
  "theme": React.PropTypes.object,
};
```

I was able to get around this error by editing the following piece in the type definitions.

```
interface StyledHTMLElement<TProps, TElement extends HTMLElement> {
  contextTypes: any; // added this line
  new (): CStyledHTMLElement<TProps, TElement>;
}
```

However, I'm not sure if that's correct. At least, it doesn't seem right to me. Any ideas on this?

Ping @faddee , it seems like you're the maintainer for the definitions.

**Comment by faddee** [comment]
Thanks, fixed in #123

**Comment by faddee** [comment]
A quick fix is to assert `MyComponent`:

```ts
(MyComponent as any).contextTypes = {
  "theme": React.PropTypes.object,
};
```

**Comment by faddee** [comment]
Hold on, it seems that it's not possible to override `contextTypes`. I get `TypeError: Cannot read property 'injectDeclaration' of undefined` since you override the `contextTypes` used by the component returned from `styled`.

Best practice should be by using a HOC, which is recommended by React when using the `context` feature anyway.

```tsx

function theme(Component) { 
  class ConnectTheme extends React.Component {
    render() {
      return <Component {...this.props} {...this.context} />
    }
  }

  ConnectTheme.contextTypes = {
    theme: React.PropTypes.object,
  };

  return ConnectTheme;
}

const MyComponent = theme(styled("div", props => ({
  "color": props.theme.color,
})));

```

**Comment by sammkj** [comment]
@faddee to solve the `TypeError: Cannot read property 'injectDeclaration' of undefined`, you would need to add `styletron` to the the `contextTypes` as well, like this:

```
const MyComponent = styled("div", (_, context) => ({
  "color": context.theme.color,
}));

MyComponent.contextTypes = {
  "theme": React.PropTypes.object,
  "styletron": React.PropTypes.object,
};
```

So the fix is not in?

**Comment by sammkj** [comment]
@faddee I agree that HOC is better than using context, perhaps `styletron-react` should ship `theme` HOC?

**Comment by faddee** [comment]
In that case it would be better to assign. 

```ts
Object.assign(MyComponent.contextTypes, {
  theme: React.PropTypes.object,
});
```

But it's nasty as hell and I wouldn't encourage anyone to do that. So the fix is off. You'll need to assert like in the example earlier.

**Comment by sammkj** [comment]
Definitely it's nasty. But, I think the definitions should cover `contextTypes` usecase as we might not know what users are gonna do with it. I also think `theme` HOC should be shipped with `styletron-react`.

**Comment by faddee** [comment]
Now the typings extends `React.StatelessComponent` which adds the `contextTypes` among others. But that doesn't mean that you're of the HOC. ;-)

**Comment by faddee** [comment]
The original question is answered so I'm closing this now.
