### ISSUE TITLE
Live Demo link from the docs isn't working

### ISSUE THREAD

**Issue by kunalgolani** [rtsao/styletron#128]
https://www.webpackbin.com/N12fnIW7G

![image](https://cloud.githubusercontent.com/assets/3034551/25995004/8e903e7c-3710-11e7-8ba7-9d134bcd4baa.png)

**Comment by rtsao** [comment]
This was graciously created by @vinniemac but it seems all the old webpack bins have been lost. I'm not sure it'll be possible to recover it so we might need to make a new demo.
