### ISSUE TITLE
Better TypeScript support for style objects

### ISSUE THREAD

**Issue by aronallen** [rtsao/styletron#136]
Having TypeScript support would be amazing.

TypeStyle already has typings, maybe most of these can be transferred over (there is some variance in the API)

**Comment by faddee** [comment]
There is TypeScript typings but it uses `React.CSSProperties` for style objects, which is quite limited. TypeStyle has done an amazing job with that part so we should definitely have a look into it.

**Comment by rtsao** [comment]
This exists now! https://github.com/frenic/csstype (the Flow version is used in styletron now)
