### ISSUE TITLE
Don't use "ad" as a class

### ISSUE THREAD

**Issue by Primajin** [rtsao/styletron#139]
By reaching 40 different class combinations Styletron will generate a class called `ad` (as in Advertisement) that is very likely to be blocked by adblockers. Please avoid classes with `ad` in it.

Remember, even Facebook had this issue: https://youtu.be/rSx5RxuaZfc?t=9m21s 😉 

```js
{Array(40).fill(1).map(function(el, i) {
      const TestComponent = styled('div', (props) => ({
        fontSize: i + 'px'
      }));
      return <TestComponent key={i}>Hello</TestComponent>;
    }
)}
```

**Comment by rtsao** [comment]
Interesting, I've definitely heard of adblockers blocking resources with `ad` in the filename (such as the example in the video you've linked) but I didn't know class names could be effected.

Is there any known adblocker with such a heuristic? Would, for example, `.had` or `.mad` be blocked?

**Comment by Primajin** [comment]
Hey I set up a codepen here:
[https://codepen.io/Primajin/full/JNgMox/](https://codepen.io/Primajin/full/JNgMox/)

### chrome without any blockers:
![screen shot 2017-05-31 at 17 36 17](https://cloud.githubusercontent.com/assets/1742115/26640325/b7bdb4b6-4627-11e7-8053-be8da11a3287.png)

### uBlock Origin:
![screen shot 2017-05-31 at 17 34 44](https://cloud.githubusercontent.com/assets/1742115/26640264/87b1daf4-4627-11e7-867b-2a5a09554977.png)

### AdBlock:
![screen shot 2017-05-31 at 17 37 57](https://cloud.githubusercontent.com/assets/1742115/26640417/f1ccb864-4627-11e7-86c8-412cc8bdec4b.png)

### AdBlock Plus:
![screen shot 2017-05-31 at 17 38 53](https://cloud.githubusercontent.com/assets/1742115/26640457/0f77abd0-4628-11e7-854e-d7b8d1c4f5d3.png)

**Comment by rtsao** [comment]
Wow, really interesting -- nice work!

I guess the quick workaround for now would be to use [the `prefix` option in the Styletron constructor](http://styletron.js.org/StyletronCore.html#StyletronCore).

```js
const styletron = new Styletron({prefix: '_'});
```

From my testing it looks like `._ad` isn't blocked.

**Comment by Primajin** [comment]
Yes that seems to be a good workaround:

### uBlock Origin:
![screen shot 2017-06-01 at 09 34 42](https://cloud.githubusercontent.com/assets/1742115/26669329/bdf49f30-46ad-11e7-80c4-f85770359da4.png)

### AdBlock:
![screen shot 2017-06-01 at 09 33 46](https://cloud.githubusercontent.com/assets/1742115/26669335/c3f51b58-46ad-11e7-8b6e-8682b1b38f70.png)

### AdBlock Plus:
![screen shot 2017-06-01 at 09 34 15](https://cloud.githubusercontent.com/assets/1742115/26669341/c7fdf3b4-46ad-11e7-9855-7c4c57ec6260.png)

**Comment by rtsao** [comment]
Another, possibly higher-performance workaround is to simply begin incrementing classnames from `ae` (thereby skipping `ad`).

Something like this would have the effect:

```js
const styletron = new Styletron();
// begin incrementing classnames from 'ae' forward
styletron.msb = 1295;
styletron.power = 2;
styletron.offset = 374;

styletron.injectDeclaration({prop: 'color', val: 'red'});
// => 'ae'
```

**Comment by Primajin** [comment]
Cool, thank you so much!
