### ISSUE TITLE
StyletronClient.injectDeclaration fails in Firefox 

### ISSUE THREAD

**Issue by davidkearns** [rtsao/styletron#14]
`sheet.rules.length` throws `TypeError: sheet.rules is undefined` in Firefox. 

It appears that Firefox does not implement `CSSStyleSheet.rules`, but instead only supports `CSSStyleSheet.cssRules` for accessing rules. 
See: https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSStyleSheet

**Comment by rtsao** [comment]
Fixed in `2.0.4`
