### ISSUE TITLE
wrong css order

### ISSUE THREAD

**Issue by tuchk4** [rtsao/styletron#140]
https://tuchk4.github.io/css-in-js-app/#/styletron

click "Render different components"

There are should not be components with black border

![image](https://cloud.githubusercontent.com/assets/5140611/26532451/d50b139e-4409-11e7-8e70-f69fb19c4fea.png)

Source here:
- https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/Styletron/Block.js
- https://github.com/tuchk4/css-in-js-app/blob/master/src/scenes/Styletron/DifferentBlocks.js

**Comment by rtsao** [comment]
This is a side effect of the generated atomic CSS classes when shorthand and longform css properties are mixed. See https://github.com/rtsao/styletron/issues/68 and https://github.com/rtsao/styletron/issues/114.

I can create a PR to your repo that resolves this by expanding the shorthand border property to individual sub-properties.

**Comment by tuchk4** [comment]
@rtsao got it. Thanks.
