### ISSUE TITLE
[styletron-react] is-valid-attr doesn't include the "for" attribute

### ISSUE THREAD

**Issue by zac-seth** [rtsao/styletron#144]
I'm using `{ styled }` to create a component wrapping the `label` element which should then be associated with a form input. When I supply an attribute of `for` to the JSX it doesn't get passed down to the rendered `label` element. There is no `for` property in `is-valid-attr`'s `htmlProps` object (`htmlFor` is supplied instead). Given what the `for` attributed is used for, this is actually breaking browser functionality (albeit in a fairly benign way).

In React's `HTMLDOMPropertyConfig` there is a mapping from `htmlFor` to `for` in `DOMAttributeNames` but this hasn't been ported into styletron-react. `htmlFor` is the DOM property API name for the `for` attribute and React is clearly using the mapping to ensure consistency with that API. 

Given that styletron-react is merely validating whether the attribute is valid and isn't actually interacting with any DOM properties, I suggest renaming `htmlFor` in `htmlProps` to `for`.

**Comment by rtsao** [comment]
This should be fixed in https://github.com/rtsao/styletron/pull/152 (released in `3.0.0-rc.1`)

**Comment by rtsao** [comment]
Also, whitelisting doesn't work like this anymore, so this isn't an issue.
