### ISSUE TITLE
README to get started isn't clear

### ISSUE THREAD

**Issue by ardok** [rtsao/styletron#155]
I have really basic app using `create-react-app`.
Followed the README and have my `index.js` to look like this:

```
import React from 'react';
import ReactDOM from 'react-dom';
import StyletronClient from 'styletron-client';
import {StyletronProvider} from 'styletron-react';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

const styleElements = document.getElementsByClassName('_styletron_hydrate_');

ReactDOM.render(
  <StyletronProvider styletron={new StyletronClient(styleElements)}>
    <App/>
  </StyletronProvider>,
  // <App />,
  document.getElementById('root')
);
registerServiceWorker();
```

I get this error when I add `<div class="_styletron_hydrate_"></div>` into `index.html`:
```
Uncaught TypeError: Cannot read property 'insertRule' of undefined
```

Without adding that `div`, I would get:
```
styletron-client.js:95 Uncaught TypeError: Cannot read property 'sheet' of undefined
```

All this error will only show up the moment I use `styled`:
```
import {styled} from 'styletron-react';
const Container = styled('div', () => ({
  width: '16px',
  height: '16px',
  display: 'inline-block',
  textAlign: 'center',
}));

const Foo = () => <Container />;  // this one causes the error there
```

**Comment by rtsao** [comment]
For the purpose of hydrating server-side rendered styles, [StyletronClient constructor takes an optional collection of `style` DOM elements](http://styletron.js.org/StyletronClient.html#StyletronClient), that should correspond to the server-side rendered style elements.

If you aren't doing SSR, you don't need to pass in anything to the constructor (it will create it's own style element for you).
