### ISSUE TITLE
Using prefix gives an error 

### ISSUE THREAD

**Issue by dsslimshaddy** [rtsao/styletron#156]
TypeError: Cannot read property 'sheet' of undefined

```
import Styletron from 'styletron-client';
import {StyletronProvider} from 'styletron-react';


const styletron = new Styletron({prefix: 'mypref'});

```

https://www.webpackbin.com/bins/-KoNumG8GMlbLKjevuYY

**Comment by rtsao** [comment]
Try:

```js
const styletron = new Styletron(void 0, {prefix: 'mypref'});
```

[Both arguments to StyletronClient are optional, the first being the SSR style elements, and the second being an options object.](http://styletron.js.org/StyletronClient.html)

But this is indeed a bit confusing; I should make the `styletron-client` and `styletron-server` constructor interface the same.
