### ISSUE TITLE
Style inheritance not allowing overrides.

### ISSUE THREAD

**Issue by Shent** [rtsao/styletron#161]
I've started styling my Core components and everything was perfect until I started to Extend them.
The extended component inherits all the core styles BUT with a priority, so I am not able to override them. This is a fundamental issue and a total blocker when you have a component composition and inheritance which we have in any React project nowadays.

Broken example is provided here: https://codesandbox.io/s/k5oLQ4YZY 
My expectation is the MenuIcon to be a lot bigger, nothing happens.
If I move the ```<Icon />``` component 1 line above, so it is rendered before the ```<MenuIcon />``` - it works but I do not want the Icon at all on this page - that makes it break.

If I implement the same example with only styled-components it works, so the issue comes from Styletron implementation for sure.

**Comment by Shent** [comment]
I have a suspicion that the way you parse the styles could be wrong if you are traversing through all the components in the order they are declared. Then the issue will be present for sure because a Core component will be seen after it's derived components and the core styles will be defined after the ones you want to prioritize. So this would not be easy to fix though. All the parsing logic needs to be reworked I guess.

**Comment by rtsao** [comment]
Hey Shent,

From your example, you have this:
```js
const GenericIcon = styled('div', {
  width: '1em',
  height: '1em',
  border: '1px solid blue',
  color: 'red'
})

class Icon extends Component {
  render() {
    return (
    	<GenericIcon className={this.props.className}>Icon</GenericIcon>
    )
  }
}

const MenuIcon = styled(Icon, {
  width: '150px',
  height: '150px'
});

```

For composition of styled elements, you need to pass in *another styled element*. So you would need to do something like this instead:

```js
const GenericIcon = styled('div', {
  width: '1em',
  height: '1em',
  border: '1px solid blue',
  color: 'red'
})

const MenuIcon = styled(GenericIcon, {
  width: '150px',
  height: '150px'
});

```

**Comment by Shent** [comment]
Hello Ryan -

I think you did not the idea of the issue I was having there.
If I am using Pure Functions as Input it is all fine, I got that. 
The problem is I have no pure functions in my project due to its specificity but Components that have functions I need to extend.
As in the example, I have a GenericIcon that has certain functions and I have to extend from it to make MenuIcon, SocialIcon, FooterIcon etc. 

Is there any way to accomplish this with Styletron or I should simply stick with StyledComponents because the concept works there, although the outputted CSS will be 30 times bigger?

**Comment by rtsao** [comment]
It seems to me that maybe your stateful class components should take your stateless, single-element styled components as props.

**Comment by Shent** [comment]
Thanks for the feedback!
However, if anyone is struggling with it this is how I've solved it on my end while discussing it here in styletron.

Implementation with Styled-Components instead:
#skin.js
```
import styled from 'styled-components';
export default getSkin => target => styled(target)`${props => getSkin(props)}`;
```
Usage: 
#YourReduxContainer.js
```
import skin from './skin';
import {plainTheme as theme} from './themes';
...
export default connect(
    mapStateToProps,
    mapDispatchToProps
)(
    skin(theme)(YourContainer) || YourContainer
);
```
Or even without Redux:
#YourContainer.js
```
skin(theme)(YourComponent);
```

**Comment by Shent** [comment]
If somehow we could change the Styletron implementation of the styled() method to act like in Styled-Components - would be awesome.
I will try to figure out what and how to help on this one.

Cheers

**Comment by rtsao** [comment]
Composition is much more flexible in v4, I think this is resolved in https://github.com/rtsao/styletron/pull/217 https://github.com/rtsao/styletron/issues/215
