### ISSUE TITLE
Composable styled api

### ISSUE THREAD

**Issue by ganemone** [rtsao/styletron#174]
Looking for some feedback on a small change to the `styled` api that could potentially allow for some interesting avenues for composition.

Looking at an example in the documentation:

```jsx
import {styled} from 'styletron-react';

const Panel = styled('div', (props) => ({
  backgroundColor: props.alert ? 'orange' : 'lightblue',
  fontSize: '12px'
}));

const DeluxePanel = styled(Panel, (props) => ({
  backgroundColor: props.alert ? 'firebrick' : 'rebeccapurple',
  color: 'white',
  boxShadow: '3px 3px 3px darkgray'
}));
```

If we changed the `styled` interface from: 

`styled(base, styleFn) → {function}` to
`styled(styleFn) → (base) → {function}`

We could rewrite the above example as:

```jsx
import {styled} from 'styletron-react';

const SimpleStyles = styled((props) => ({
  backgroundColor: props.alert ? 'orange' : 'lightblue',
  fontSize: '12px'
}));

const FancyStyles = styled((props) => ({
  backgroundColor: props.alert ? 'firebrick' : 'rebeccapurple',
  color: 'white',
  boxShadow: '3px 3px 3px darkgray'
}));

const Panel = SimpleStyles('div');
const DeluxePanel = compose(SimpleStyles, FancyStyles)('div');
```

You could further break this down into something like this (somewhat contrive) example:

```jsx
import {styled} from 'styletron-react';

const Small = styled({
  fontSize: '12px',
});

const SimpleAlert = styled((props) => ({
  backgroundColor: props.alert ? 'orange' : 'lightblue',
}));

const Shadow = styled({
  boxShadow: '3px 3px 3px darkgray'
});

const FancyAlert = styled((props) => ({
  backgroundColor: props.alert ? 'firebrick' : 'rebeccapurple',
  color: 'white',
}));

const Panel = compose(Small, SimpleAlert)('div');
const DeluxePanel = compose(Small, Shadow, FancyAlert)('div');
```

It is a minor change, but potentially encourages designing your styled components in a way where you compose base styles throughout your application. There are also several variations on this API that could achieve the same results. Such as `import {styledDiv}` or `styled('div')(styleFn)`, etc. The important thing is encouraging unary functions for composability.

Thoughts? Not sure if this is a good pattern or not.

**Comment by bzalasky** [comment]
@ganemone Personally, I like this approach. You can enable this kind of API with a small higher-order component using Recompose.

```javascript
import {mapProps} from 'recompose';

const styled = styles => mapProps(
  ({style, ...props}) => ({...props, style: {...styles, ...style}})
);

export default styled;
```
One thing that's unintuitive about how this works is the way the passed in styles are extended by the style prop. The reason it's like this is because as you compose multiple styled components, the passed in styles become props to their children, and ultimately the base component.

You can test that this works as expected by unwrapping the base component with recursion (assuming Enzyme is in play here):

```javascript
const unwrapStyles = (wrapper) => {
  let child = wrapper.childAt(0);

  if (child.length === 0) {
    return {};

  } else {
    return _.extend(unwrapStyles(child), child.prop('style'));
  }
};
```

**Comment by rtsao** [comment]
v4 has a new, more flexible composition API that address this use case: https://github.com/rtsao/styletron/pull/217
