### ISSUE TITLE
Support Jest (--env jsdom) with styletron-legacy

### ISSUE THREAD

**Issue by shanshanzhu** [rtsao/styletron#178]
We are using styletron-legacy v2.5.1
and when we run jest, and we create a component as follows:
```
export const View = styled('div', () => ({
  width: '100%',
  height: '100%'
}));
```
Then when we ran the jest file in jsdom env
```
it('renders View', () => {
  const wrapper = shallow(<View />);
  expect(View).toBeTruthy();
});
```
Throws an error
```
TypeError: Cannot read property 'querySelector' of undefined
    at existingStyleElement (node_modules/styletron-legacy/index.js:184:11)
    at injectStylesIntoHead (node_modules/styletron-legacy/index.js:128:17)
    at flushToStyleElement (node_modules/styletron-legacy/index.js:169:5)
```
In the index.js
https://github.com/rtsao/styletron/blob/v2.5.1/packages/styletron-legacy/index.js#L184
global.document is defined, but document is undefined
The test pass when we add this to the top of index.js
```
var document = global.document;
```
suggested fix, use npm package global
```
var document = require('global/document');
```

**Comment by rtsao** [comment]
Thanks for the bug report, I've made a corresponding issue in the styletron-legacy repo: https://github.com/rtsao/styletron-legacy/issues/2.

Should be a straightforward fix.
