### ISSUE TITLE
Add a way to inject scoped @keyframes

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#18]
This could probably done in a fairly separate fashion with its own API.

**Comment by teonik** [comment]
That would be awesome.

**Comment by alisd23** [comment]
Are keyframes supported at all yet?

**Comment by rtsao** [comment]
Injecting keyframes isn't supported yet, but I'm working on this. You can expect a proposal/PR in the coming days.

**Comment by milesj** [comment]
Good to know! I've been waiting to add Styletron support to my Aesthetic librarry (https://github.com/milesj/aesthetic). Font faces and keyframes are the last remaining features.

**Comment by rtsao** [comment]
Created a RFC for this here: https://github.com/rtsao/styletron/issues/92

**Comment by rtsao** [comment]
Closed in https://github.com/rtsao/styletron/pull/217
