### ISSUE TITLE
injectRawDeclaration problem with last stable version (2.5.7)

### ISSUE THREAD

**Issue by timhecker** [rtsao/styletron#180]
Hi,
using your last stable version (via `yarn add styletron`) I had an error: `injectRawDeclaration is not a function`. Installing the `3.0.0-rc.1` everything works. 
This will be fixed with the v. 3 release?

Thanks

**Comment by Ayc0** [comment]
I had the same after upgrading to `3.0.0-rc.2` (i was previously in `2.5.10` and it worked)

**Comment by rtsao** [comment]
This should not be a problem in non-rc versions of 3.x (i.e. `3.0.0`)
