### ISSUE TITLE
[Suggestion] Support prefixes for injected CSS class names

### ISSUE THREAD

**Issue by bmcdorman** [rtsao/styletron#187]
I recently encountered an issue where #icons from font awesome would suddenly jump to a different position on the page or have other styling anomalies after my relatively large application had been running long enough.

Font awesome uses the CSS class "fa" on icon definitions, and I eventually discovered that styletron was injecting a class "fa" that collided with font awesome's definition, making the icons apply the injected declaration. My temporary work-around is to manually modify font awesome's class names, but this isn't an ideal solution.

My suggestion is to allow injected declarations by styletron to optionally be prefixed by a string, preventing name collisions like the one I experienced.

Thanks for styletron! It's great. 😄

**Comment by bmcdorman** [comment]
Aaand it appears that styletron-core can take a prefix in its constructor. Nevermind... 😅

**Comment by vicapow** [comment]
just wanted to say we just ran into this issue, too. cf conflicts with superfine

**Comment by rtsao** [comment]
`styletron-engine-atomic` takes a [`prefix` option](https://github.com/styletron/styletron/tree/master/packages/styletron-engine-atomic#constructoropts-prefix-string-hydrate-htmlstyleelement-container-element) for this.
