### ISSUE TITLE
Missing client-side media attribute 

### ISSUE THREAD

**Issue by stevenbenisek** [rtsao/styletron#19]
Client-side media queries don't work because the mediaSheets lack a matching media attribute [https://github.com/rtsao/styletron/blob/master/packages/styletron-client/src/styletron-client.js#L81-L83](https://github.com/rtsao/styletron/blob/master/packages/styletron-client/src/styletron-client.js#L81-L83)

PR on its way 😄

**Comment by rtsao** [comment]
Nice catch, thank you! Styletron has been primarily used in production in conjunction with server rendering so this wasn't caught earlier, haha.

**Comment by rtsao** [comment]
More reason for: https://github.com/rtsao/styletron/issues/9 😉

**Comment by stevenbenisek** [comment]
Happy to help. Loving Styletron 😛
