### ISSUE TITLE
Document: styleProps

### ISSUE THREAD

**Issue by AlexMSmithCA** [rtsao/styletron#192]
As of #169, there exists a specific prop (`styleProps`) which are not passed to the inner component.

This feature is not yet documented.

CC: [@davidkearns](https://github.com/davidkearns)

**Comment by jaxxreal** [comment]
Better little docs than nothing, right?

https://gist.github.com/jaxxreal/a0831c2f1ec5be1f3ef15034bb49cf4b.

I made that for my fellows, probably will be useful till the official doc will come.

**Comment by rtsao** [comment]
Working on some repo and doc improvements before I release the final 3.0.0 version.

I have an idea for an alternative to `styleProps` that might be interesting: https://github.com/rtsao/styletron/issues/196

**Comment by rtsao** [comment]
The proposal in #196 has been landed. Docs have been updated in https://github.com/rtsao/styletron/pull/217
