### ISSUE TITLE
Crashes under Enzyme shallow rendering

### ISSUE THREAD

**Issue by ksheedlo** [rtsao/styletron#2]
I have some tests that use [Enzyme](http://airbnb.io/enzyme/) to shallow render a React component that's built with react-stylematic. Lately, I get the following error message when I try to run my test. I'm using tape in node.

```
/Users/ken/unpm-code/chameleon-render/node_modules/styletron/index.js:184
  return document.querySelector('style[data-styletron]');
         ^
ReferenceError: document is not defined
    at existingStyleElement (/Users/ken/unpm-code/chameleon-render/node_modules/styletron/index.js:184:10)
    at injectStylesIntoHead (/Users/ken/unpm-code/chameleon-render/node_modules/styletron/index.js:128:17)
    at flushToStyleElement (/Users/ken/unpm-code/chameleon-render/node_modules/styletron/index.js:169:5)
    at RawTask.call (/Users/ken/unpm-code/chameleon-render/node_modules/asap/asap.js:40:19)
    at flush (/Users/ken/unpm-code/chameleon-render/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:419:13)
```

**What I expected to happen:** I should be able to shallowly render react-stylematic components using Enzyme in my tests, without crashing the test harness.

**What actually happened:** Styletron accessed a property of `document` in an environment where `document` was not defined. This crashed my tests.

**Steps to reproduce:** Build a component (call it `MyComponent`) using react-stylematic. Write a shallow rendering test:

```
import {shallow} from 'enzyme';

tape('This crashes', function assert(t) {
  const component = shallow(<MyComponent />);
  t.end();
});
```

It should crash at the end of the test.

**Comment by rtsao** [comment]
https://github.com/rtsao/styletron/blob/master/index.js#L78 Should prevent a 'flushToStyleElement' from being scheduled (like you are experiencing).

I think enzyme is doing something with cheerio that results in 'document' being defined. I'll dig further into this. In the meantime, if you do standard shallow rendering without enzyme you should not have any issues.

**Comment by ksheedlo** [comment]
I'm working around this for now using this code:

```js
/* global global */

// Workaround for https://github.com/rtsao/styletron/issues/2
if (!global.document) {
  global.document = {
    querySelector: () => {
      return {
        appendChild: () => {}
      };
    },
    createTextNode: () => {}
  };
}
```

**Comment by rtsao** [comment]
I found why this is happening with enzyme: https://github.com/airbnb/enzyme/blob/1c4fdb65ff1cdfdf14ac3d1510132193b6e72e33/src/Utils.js#L149

Apparently the enzyme folks have put in a workaround that is causing document to be defined, so styletron thinks it actually exists when in reality it is just a mock empty object. I think I'll just make the styletron check a bit more robust as a workaround for that workaround.
