### ISSUE TITLE
Latest version (3.0.1) doesn't work with CRA

### ISSUE THREAD

**Issue by andreiduca** [rtsao/styletron#207]
### Steps to reproduce:

1. Create a new app with `create-react-app`
2. Add `styletron` dependencies: `yarn add styletron styletron-client styletron-react`
3. Wrap the main `App` component in a `StyletronProvider` component:
```jsx
ReactDOM.render(
    <StyletronProvider styletron={styletronInstance}>
        <App />
    </StyletronProvider>,
    document.getElementById('root')
);
```
4. Build the app with `yarn build` and launch

The app doesn't render and a Console error shows
```console
VM353 main.35ec9e17.js:1 Uncaught TypeError: u.a is not a constructor
    at Object.<anonymous> (VM353 main.35ec9e17.js:1)
    at t (VM353 main.35ec9e17.js:1)
    at Object.<anonymous> (VM353 main.35ec9e17.js:1)
    at t (VM353 main.35ec9e17.js:1)
    at VM353 main.35ec9e17.js:1
    at VM353 main.35ec9e17.js:1
```

---
Note: it seems that Styletron core components are extracted from the compiled js bundle and are outputted to a different location. The following 2 files are created on `yarn build` (they were previously non existent):

```
/build
 |-- static
      |-- media
           |-- browser.es5.9d690c38.mjs
           |-- browser.es5.aefe89ad.mjs
```

**Comment by andreiduca** [comment]
I couldn't find a quick fix or a workaround for this. I reverted back to 2.5.x until this is fixed.

**Comment by danielstocks** [comment]
Possibly related to this:

https://github.com/rtsao/styletron/issues/208

**Comment by rtsao** [comment]
Looks like CRA doesn't like the `.mjs` extension and is treating it as a static asset rather than a JS dependency.

**Comment by rtsao** [comment]
Looks like the fix hasn't been released yet: https://github.com/facebookincubator/create-react-app/pull/3537

**Comment by rtsao** [comment]
This should be resolved in `3.0.2`. Going to avoid `.mjs` until it is better supported.

**Comment by andreiduca** [comment]
Tested in 2 different projects. I confirm it works. Thanks!

**Comment by danielstocks** [comment]
@andreiduca I guess you can also close this issue if it's resolved :)
