### ISSUE TITLE
Styletron v4

### ISSUE THREAD

**Issue by rtsao** [rtsao/styletron#215]
I've been thinking a lot about the Styletron API recently and want to make some significant API improvements.

## New creation/composition APIs

The current polymorphic `styled` function has multiple uses:
1. Creating a new styled component from an html element name or React component
2. Composing an existing styled element component and new styles to create a new styled element component. 

This is simple, but it's not very flexible and type polymorphism can lead to confusion in the case of styled components vs regular components.

I propose something like this:

```js
import {
  styled,    // create new styled component
  withStyle, // compose new styled component, shallow merge
  withStyleDeep,  // compose new styled component, deep merge
  withTransform,  // compose new styled component, arbitrary style transform
  withContext, // compose new styled component, merge in contextTypes
  withBase,    // compose new styled component, change the base
} from "styletron-react";

const A = styled('div', {color: 'red'});
const B = withBase(A, 'span');
const C = withStyle(A, {':hover': {color: 'black', background:'red'}}); 
const D = withStyleDeep(C, {':hover': {background:'red'}}); 
const E = withTransform(A, (style, props) => ({...style, color: 'purple'})); 

```

## Styled prop namespace (for React)

This is already in v3, but props prefixed by `$` will not get passed to the underlying element (so React attribute warnings are not triggered). This replaces `styleProps`.

For example:
```js
const Box = styled('div', ({$variant}) => {
  const width = {
    sm: "10px",
    lg: "20px"
  }[$variant];
  return {width}
});
```

### New built-in props

- `$ref` - replaces `innerRef`
  - ```js
    <Foo $ref={() => this.foo = this} />
- `$as` - render callback to dynamically change the base
  - ```js
    <Foo $as="span">Hello World</Foo>
    <Foo $as={Link}>Hello World</Foo>

## Engine de-coupling

Styletron has always had an atomic rendering engine, but this will now be de-coupled. This won't incur any performance cost, but opens up the opportunity for alternative engines in the future (without bloat for people who don't want it).

```js
import {BrowserEngine} from "styletron-engine-atomic";
import {Styletron} from "styletron";
import {Provider} from "styletron-react";

const engine = new BrowserEngine();
const styletron = new Styletron(engine);

<Provider styletron={styletron} />
```

## Flow typing
I'm committed to having really good Flow type support, including:
- Typed styled objects
- Correct types even if there's style transformations (see below)

## Plugins

Folks have asked for things like: https://github.com/rtsao/styletron/issues/35 which change the style object type. I want more customizability to accommodate that while preserving good type inference and portability.

I also want to allow for more customizability of things like vendor prefixing.

My current thinking is there should be engine-specific plugins which don't affect the shape of the authored style objects, and style plugins (added to the components themselves) which can affect the shape of authored style objects.

In summary:
- Engine plugins 
  - Vendor prefixing (likely engine-specific implementations for max perf)
  - Media query sorting (for atomic engine)
  - etc.
- Styler plugins
  - Default units
  - Custom properties
  - Bidi
  - etc.

## Wrapper API

I want something to be able to apply a wrappers but still have style composition work properly. I'm not sure about the exact API, but it might look something like this:

```js
const A = styled('div', {color: 'red'});
// Default wrapper is identity function (e.g. StyledElement => StyledElement)

// example wrapper that consumes context and sets a prop based on its value
const B = withWrapper(A, (StyledElement) => (props) => (
  <Consumer>
    {contextValue => <StyledElement {...props, arbitraryProp: contextValue}/>
  </Consumer>
));

// composition works still, but C has the same wrapper as B
const C = withStyle(B, {color: 'green'});

```

There should be a way to create a `styled` function with a particular wrapper as well, so all elements could have a wrapper by default.

**Comment by henriquea** [comment]
@rtsao this is looking good. The composition APIs would come handy! Did you have any thoughts on a helper to inject global styles something similar with `injectGlobal` in styled-components?

**Comment by schnerd** [comment]
@rtsao Nice, no red flags here.

Child combinators (#27) still on the wishlist though, maybe with a similar API to [styled-components](https://www.styled-components.com/docs/advanced#referring-to-other-components) or [glamorous](https://glamorous.rocks/examples/#component-as-a-selector).

**Comment by cloudkite** [comment]
Hi @rtsao, you mention using Styler plugins to implement Default units. Do you have an example of how this works? Thanks
