### ISSUE TITLE
Whenever there's a version difference between apps and imported styletron components, app crashes

### ISSUE THREAD

**Issue by jasonbarone** [rtsao/styletron#266]
I'm noticing behavior with styletron where if any individual component's styletron version is out of sync with the app you're importing them too, the app crashes due to the following error:

```
Error: A Styletron styled component was rendered, but no Styletron engine instance was provided in React context. Did you forget to provide a Styletron engine instance to React context via using the Styletron provider component? Note: Providers and Consumers must come from the exact same React.createContext call to work. If your app has multiple instances of the "styletron-react-core" package in your node_module tree, your Provider may be coming from a different React.createContext call, which means the styled components will not recieve the provided engine instance. This scenario can arise, for example, when using "npm link".
```

How do you deal with this behavior, in terms of creating reusable shareable components? If we build a component using one of the latest versions, such as 4.3.3, but our app uses 4.3.4, the app seems to crash because there will be 2 different dependencies in the node_modules tree. I've tried this on a few different apps and I'm getting the same behavior. If we're using components in a FusionJS app, which loads styletron via the styletron fusion plugin, it's even harder to deal with because its styletron dependency is already specified in the fusion plugin and loaded into the Fusion app.

**Comment by rtsao** [comment]
This is an unfortunate side effect of the new React 16.3 `React.createContext API`. The old API used string keys so context consumers and providers could be anywhere/duplicated/etc.

For the new API to work, all Consumers and Providers must come from the exact same `React.createContext` call to communicate correctly. This means if there are multiple instances of `styletron-react` in node_modules, they can’t communicate with each other and you see the error.

You can use peer dependency to ensure only one version is installed. (fusion-plugin-styletron-react has a peer dependency on styletron-react and expects the host app to install it)

**Comment by jasonbarone** [comment]
Makes perfect sense. I updated all dependencies to remove styletron-react and move to devDep and peerDep. I submitted a bug on fusion-plugin-styletron-react as well, which I can probably close out as well.

Might be helpful to clarify that in the docs for people interest in building individual packages with styletron. I can put up a PR later this week if that helps.

**Comment by rtsao** [comment]
I've been meaning to file an issue on React regarding this for a while. Finally made one to kick off a discussion: https://github.com/facebook/react/issues/13346

**Comment by shanshanzhu** [comment]
I ran into the error on jest testing but not on acutual browser . We finally found out a couple solutions.

1. Follow the styletron instruction for `Server-side rendering` and add <Provider> to the component, if you want the jest test env to be `server`.
2. Change Jest test environment o browser environment.

Both works for us
