### ISSUE TITLE
[styletron-react] - add higher-order component to inject styles

### ISSUE THREAD

**Issue by umidbekkarimov** [rtsao/styletron#33]
Greetings! yesterday saw blog post about `styletron` and I'm superexcited  about it, wanted to test it in current project but found that it doesn't have hoc for React. 

That would be great to have HOC like this: 

```javascript
import {withStyles} from 'styletron-react';

const enhancer = withStyles((props) => ({
  foo: {
      color: props.alert ? 'orange' : 'lightblue',
  },
  bar: {
     backgroundColor: props.alert ? 'orange' : 'lightblue',
  },
}))

const Baz = (props) => {
  return (
    <div className={props.classes.foo}>
      <div className={props.classes.bar}>Baz</div>
    </div>
  )
}

export default enhancer(Baz)
```

**Comment by rtsao** [comment]
This actually used to exist 😆. I changed the API from a HOC to the current interface (inspired by styled-components) in this commit: https://github.com/rtsao/styletron/commit/09dd07c2f5ae62c3a61e00a8f03d607554c0bf3d

In my eyes, the newer API seems better, but I suppose there's room to have both. I'm interested to hear more on what the HOC does better than the styled component helpers.

**Comment by umidbekkarimov** [comment]
> I'm interested to hear more on what the HOC does better than the styled component helpers.

In my case - get rid of migration headaches (currently i have ~116 components that use HOCs :))

**Comment by krainboltgreene** [comment]
Also, it's very easy to stack HOC's using the experimental syntax:

``` javascript
import {withStyles} from "styletron"
import {falcored} from "react-falcor"
import {connect} from "react-redux

@withStyles(...)
@falcored
@connect
export default class Profile extends Component {
  static propTypes = {
    name: PropTypes.string.isRequired,
    src: PropTypes.string.isRequired
  }

  render () {
    const {name} = this.props
    const {src} = this.props

    <section>
      <Heading as="page">
        {name}
      </Heading>
      <Avatar src={src} />
    </section>
  }
}
```

**Comment by deepsweet** [comment]
reason why I have found this issue – ❤️ https://github.com/acdlite/recompose/

going all the way with HOCs and actually want to try styletron the same way. IMO styled-components approach is good and handy for using with React type strings like `'div'` or `'span'`, but for Components it's really a common practice to use HOC (redux, react-dnd, ...).

it's easy to create a custom "proxy" wrapper, but...

**Comment by faddee** [comment]
Another use case would be the possibility to use the official `ReactCSSTransitionGroup` with custom class names. You could "hack" that one too, but that's not preferable.

**Comment by tabazevedo** [comment]
@umidbekkarimov I built this recently for the use case of having an easier transition from css modules to styletron: https://github.com/tabazevedo/styletron-connect

Fits your use case too.
Feel free to contribute if you feel like there's anything missing!

**Comment by rtsao** [comment]
@tabazevedo Nice work! 🎉

I'm going to add a community/ecosystem section to the README for other libraries built on Styletron so folks can find it more easily.

**Comment by josepot** [comment]
In our projects we use both [ramda](http://ramdajs.com/) and [recompose](https://github.com/acdlite/recompose), so we've created the following helper HOC:

```js
// src/lib/tm-with-styles.js

import R from 'ramda';
import { styled } from 'styletron-react';

export default R.compose(R.curry, R.flip)(styled);
```

And this is a fancy usage of it:

```js
import R from 'ramda';
import { compose, mapProps } from 'recompose';

import withStyles from 'tm-with-styles';
import withTransitions from 'tm-with-transitions';

export const HoverBox = compose(
  withTransitions(R.propEq('isHovering', true), 200),
  withStyles(({ transitionState }) => {
    const [opacity, top] = transitionState === 'NORMAL'
      ? [1, '10px']
      : [0, '15px'];
    return {
      padding: '10px',
      position: 'absolute',
      width: '83%',
      right: '0',
      opacity,
      top,
      transition: 'all 0.2s ease',
    };
  }),
  mapProps(R.omit(['transitionState', 'isHovering']))
)(ShadowedWrapper);
```
In case you are wondering: `withTransitions` is another HOC helper that uses the low-level API of [CSSTransitionGroup](https://github.com/reactjs/react-transition-group) in order to enhance the component by adding the property `transitionState` which can have one of the following values: 'INIT', 'NORMAL' or 'ENDING', depending on the state of the transition.

What I'm trying to say is that I think that a curried and "flipped" version of the `styled` function could be very useful... I use it all the time. 😄

**Comment by krainboltgreene** [comment]
Haha, that's awesome! It's nice to know I'm not the only one doing this sort of thing!

**Comment by rtsao** [comment]
Closing, see https://github.com/rtsao/styletron/pull/129
