### ISSUE TITLE
Components returned from "styled" have no backing instance, preventing refs from being set

### ISSUE THREAD

**Issue by sammkj** [rtsao/styletron#36]
For example,

```
class Parent extends Component {
  render() {
    return (
      <div>
        // ChildComponent is a styletron component.
        // this.childComponent is undefined
        <ChildComponent ref={(c) => { this.childComponent =  c; }}
      </div>
    );
  }
}
```

**Comment by rtsao** [comment]
Yeah, `styled` is currently returning a stateless functional component which has no backing instance. It needs to be changed so it returns a full React component.

**Comment by lostpebble** [comment]
It appears that styletron is still returning stateless functional components from the `styled` method...

I am unable to set `ref={}` on the returned components.

**Comment by Shent** [comment]
lostpebble , exactly that is why I stopped using it and switched to styled-components's styled() instead.
Styletron breaks my connect() and custom decorators.

**Comment by rtsao** [comment]
@lostpebble 

Styled components are inherently stateless and can't have any methods. However, you may want to set refs on the underlying elements to get access to the DOM elements to call DOM methods, etc. You can do this with the `innerRef` prop.

For example: https://codesandbox.io/s/lOERlQW0V

```js
import React, { Component } from "react";
import { render } from "react-dom";
import { styled, StyletronProvider } from "styletron-react";
import Styletron from "styletron-client";

const Foo = styled("input", {
  color: "blue",
  padding: "12px",
  borderStyle: "solid",
  borderWith: "1px",
  borderColor: "blue",
  ":focus": {
    color: "red",
    borderColor: "red"
  }
});

class Bar extends Component {
  constructor() {
    super();
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(e) {
    this.input.focus();
  }

  render() {
    return (
      <div>
        <div>
          <Foo
            placeholder="i am an input"
            innerRef={a => {
              this.input = a;
            }}
          />
        </div>
        <button onClick={this.handleClick}>focus the input</button>
      </div>
    );
  }
}

const App = () =>
  <StyletronProvider styletron={new Styletron()}>
    <div>
      <Bar />
    </div>
  </StyletronProvider>;

render(<App />, document.getElementById("root"));
```

**Comment by lostpebble** [comment]
@rtsao Thanks, that does the trick! Just couldn't find reference to it anywhere in the docs.

I guess it is a standard syntax for wrapper components? But still would be good to have an indication somewhere as working with `ref` is quite a common occurrence.

**Comment by jonatanramhoj** [comment]
When using "innerRef" a proxyComponent is returned, not the actual DOM element. Advice please.
