### ISSUE TITLE
Unable to see README on npm

### ISSUE THREAD

**Issue by ajduke** [rtsao/styletron#40]
https://www.npmjs.com/package/styletron

![image](https://cloud.githubusercontent.com/assets/1594650/21074183/a47e2ec6-bf18-11e6-83e2-71eddfd5d671.png)

Cool project, btw

**Comment by rtsao** [comment]
This is actually a problem with the npm registry and how Lerna works: https://github.com/lerna/lerna/issues/64

I'm not sure there's anything to be done until this is fixed upstream, unfortunately.

**Comment by hzoo** [comment]
Fixed!! https://github.com/lerna/lerna/issues/64 😍

**Comment by rtsao** [comment]
Resolved! 🎉
