### ISSUE TITLE
How to define global styles

### ISSUE THREAD

**Issue by zerkalica** [rtsao/styletron#44]
How to define global styles in styletron?

```
{
  '@global': {
    html: {globalStyles},
    button: {globalStyles}
  },
  button: {localStyles}
}
```

Like in [jss-global](https://github.com/cssinjs/jss/issues/324)

**Comment by rtsao** [comment]
Hey @zerkalica, currently Styletron doesn't provide an API for global styles.

Although I think there's always a need for global `html`/`body` resets, in general, the main use case for Styletron is apps that avoid "global" CSS. That said, I may look into I may look into ways to possible add this in the future, just so the existing client/server-rendering mechanisms can be utilized for global CSS.
