### ISSUE TITLE
Forgive me for this

### ISSUE THREAD

**Issue by chill31** [rtsao/styletron#440]
this issue is not related with the package at all.
In the home page of the styletron package -> [here](https://styletron.org) , there's a slight grammatical error. <br>
![image](https://github.com/styletron/styletron/assets/89910163/df5c5291-0ca2-4b0f-8914-c2b978b671f5)

It shouldn't be **an universal**, it should be **a universal**.
Yeah you can hate me for these kinds of stuff

**Comment by netojose** [comment]
No, it's correct.
if the next word after article start with a vowel (in this case "u"niversal), the correct is use "an".
Examples:

> an elephant
> an apple
> 

You only should to use "a", if the next word start with consonant, for example:

> a teacher
> a boy
> a car
>

**Comment by chill31** [comment]
![image](https://github.com/user-attachments/assets/9f4aeca8-4cc7-4fb5-a0f6-a0dbb5732341)
![image](https://github.com/user-attachments/assets/6df6a589-a021-46ac-87ea-a458dbd5d1c1)

To summarize, "an" only comes before vowel "sound"
I have given photos of both the explanation and the closest example I could find.

**Comment by leyanlo** [comment]
> ![image](https://github.com/user-attachments/assets/9f4aeca8-4cc7-4fb5-a0f6-a0dbb5732341)
> 
> ![image](https://github.com/user-attachments/assets/6df6a589-a021-46ac-87ea-a458dbd5d1c1)
> 
> 
> 
> To summarize, "an" only comes before vowel "sound"
> 
> I have given photos of both the explanation and the closest example I could find.

The second screenshot supports the idea that it should read `a universal toolkit`
