### ISSUE TITLE
inferno support

### ISSUE THREAD

**Issue by batwicket** [rtsao/styletron#50]
The styletron-inferno package didn't make it into 2.0.1.. was there a reason? 

I took a look at forking the current styletron-react, but the tests make use of react-specific test utilities and i don't have time to dig into possible design/implementation differences between Inferno and React. I really wanted to use 'styled()'. It looks like I might be able to just create my own version of the StyledElement class. Do you think this would make sense?

thanks!

**Comment by rtsao** [comment]
Haha yeah, there was lots of API churn on styletron-react, so for simplicity I dropped it. That said, I think styletron-react is stable now so adding it back in makes sense! PR would be appreciated!

**Comment by batwicket** [comment]
Looked at it but the styletron-react tests were quite a bit more involved than the older styletron-inferno ones and I didn't know enough to say whether the test coverage would be sufficient for any changes i might make. 

If styletron can rest comfortably on top of the React component interface (i haven't actually seen a formal definition.. perhaps there is one) then no worries.. there are quite a few VDOMs about and making a separate package for each seems like work.

**Comment by batwicket** [comment]
I got the basic demo at http://www.webpackbin.com/N12fnIW7G running with Inferno after subbing in the Inferno component requires and pulling in the comfortably small/simple StyletronProvider code. Just saying.. no guarantees.

**Comment by wagerfield** [comment]
Is the intention for `styletron-inferno` to follow the design and API of `styletron-react`? 

I'm using `styletron-inferno` as it currently stands (`2.0.1-beta.1`) with the `connectToStyles` method. If the plan is for it to follow suite of `styletron-react`'s `styled` function, I could take a look at implementing this if you like @rtsao?

**Comment by rtsao** [comment]
@wagerfield Yeah, it's meant to be the same. But in the early days, when the API was pretty unstable, I just deleted the inferno variant because it was somewhat of a hassle to make changes in both versions.

If you wanted to take a stab at it that'd be awesome!

**Comment by wagerfield** [comment]
@rtsao I had a look at it and I'm going to have to concede—I've not used TypeScript before, so it's pretty difficult to get my head into the code. Could I please defer this back to you?

Would it be much work cloning the `styletron-react` package and doing the necessary rewiring for inferno? I would _really_ like to use the `styletron-inferno` package as you intend it to be with the matured `styled` HoC function.

**Comment by faddee** [comment]
TypeScript has nothing to do with the code. It's just a declaration file for those who use TypeScript. So if you copy `styletron-react` just remove `index.d.ts`.

**Comment by wagerfield** [comment]
@faddee ok, I'll take another look.

**Comment by wagerfield** [comment]
Figured it all out now and have a nice succinct port of `styletron-react`.

Should have a PR ready by the end of tomorrow @rtsao.

**Comment by wagerfield** [comment]
Quick update—almost ready to create a PR. All code is written, as is the README and tests. All tests are passing par 1...but the reason the test is failing is due to a bug in Inferno's test utils. 

I filed a bug [here](https://github.com/infernojs/inferno/issues/755#issuecomment-274256590), where you will see that it has nothing to do with Styletron, but is preventing me from querying the output from Inferno which I need for the tests to work!

As soon as this bug is resolved with Inferno (I'm working to fix this myself right now) then I will create the PR.

**Comment by kenvunz** [comment]
@wagerfield do you mind putting your PR somewhere as WIP so I can try it out? While waiting for Inferno folks fix up the issue?

**Comment by wagerfield** [comment]
@kenvunz @rtsao I've joined the Inferno team and have been working on the `inferno-test-utils` for this past week. I hope to have them wrapped up by the weekend, ready to ship in the next update. `styletron-inferno` will be able to ship moments after Inferno's test utils are published...hold in there.
