### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by faddee** [rtsao/styletron#51]
Wrote a [TypeScript declaration file for `styletron-react`, `styletron-client` and `styletron-server`](https://gist.github.com/faddee/452f1d294765d7cead9861acfe9eac6a) and I thought it would spare anyone a couple of hours if I shared it.

**Comment by rtsao** [comment]
@faddee That is so awesome! Could these be added to https://github.com/flowtype/flow-typed?

**Comment by faddee** [comment]
I haven't got a fair chance of working with Flow but I'm pretty sure these definitions only work with TypeScript. It's possible to add those to the package so you automatically get TypeScript covered when installing Styletron but I didn't create a PR since these definitions only covers three of all your packages. But if you would be interested in starting with just these three I would be happy to help you out?

**Comment by rtsao** [comment]
😂 Oh I meant to link to: https://github.com/DefinitelyTyped/DefinitelyTyped which is the TypeScript equivalent of flow-typed.

**Comment by faddee** [comment]
I would recommend to add the declaration files to your bundled packages. In that way you have the control: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by faddee** [comment]
Created #52 so I'll close this.

**Comment by nikushx** [comment]
Can you share the declaration file(s) again? Currently working and running into many issues relating to this. Link is broken.
