### ISSUE TITLE
Static / global styles outside of React

### ISSUE THREAD

**Issue by PhiLhoSoft** [rtsao/styletron#55]
https://github.com/rtsao/styletron#static-styles shows how to associate a style to a tag name, if I understood correctly. But the code is React only.
Is there a way to inject static / global style (eg. styling html or body tags) on the server? Or outside of React?

**Comment by rtsao** [comment]
Not yet. Right now Styletron only handles atomic CSS classes.

Styling body/html tags is definitely an important use-case, but it hasn't been a priority yet in Styletron as at work we use server-rendering so we can just inlined these static global styles into the page markup into the head in a plain style element.

That said, it's something I'd like to support in the future, ideally as a mixin or something.

**Comment by PhiLhoSoft** [comment]
OK, I suppose I will leave this open to track this feature, or feel free to close it if you prefer.

I test Styletron with other libraries: https://github.com/PhiLhoSoft/css-in-js-perf-tests/tree/complex-test-case (will be merged to the original project, if it goes well), and that's what I did for libraries without "proper" management of globals (either it is out of their scope, or not done yet).

My way works because the global styles are still simple (static), so I can manage them with primitive code, but it might lack auto-prefixing or managing complex values, media queries, etc.

**Comment by rtsao** [comment]
Styletron is opinionated towards component-based CSS so I think true global styles support will probably never be added.

Ideally global styles are minimized to a small reset, where I think rendering a `<style>` element is sufficient for most use cases.
