### ISSUE TITLE
Collision between instances of Styletron

### ISSUE THREAD

**Issue by micaste** [rtsao/styletron#61]
Hi,

While upgrading react from 0.14.x to 15.x we stumbled upon this issue https://github.com/facebook/react/issues/6467
After looking at the different solutions existing (mainly inline-style-prefixer or a css in js library), we found your library great and are very excited about migrating to use it ! We did the choice of css in js over only an inline prefixer because it also brought a nice solution for selectors.

While evaluating Styletron, we were questioning how two instances of Styletron would coexist in the same application. In your live demo, we saw that the classes generated were a, b, c, ... What if I have a dependency (let's say a UI library) that also uses Styletron with a different stylesheet ? The classes are currently colliding: 
http://www.webpackbin.com/41GtF_nEG

As the success of Styletron increases, I think that this issue might occur soon enough. I do not look at how the other css in js libraries are dealing with this issue. My guess is that they might rely on the hashing function  to have a low collision probability .

I see only one proper solution to this issue:
- Styletron should append a className prefix. Following that, all the classes generated would be 'myLib-a myLib-b ...' and different instances of Styletron would not collide.

I agree that several libraries using different instances of Styletron defeat the purpose of 'virtual css', but I think that it is the best we can do => there is no way we can share the instance with the dependencies.

Adding a constructor argument would make the api more complicated, but I think that the prefix is necessary. I am thinking about a constructor argument (optional or not) for example with a randomly generated set of characters as a fallback.

**Comment by micaste** [comment]
Hi, I just saw that there is an option for this in the styletron-core, by extension in the styletron-client too.

Adding `{prefix: 'myPrefix-'}` as the second argument of the constructor fixes the issue and answers my concern.

I would suggest making this option available in the documentation, more especially in the section 'For framework and library authors' since it is to my mind a must-have.

**Comment by rtsao** [comment]
Thanks for bringing this up, sorry that wasn't documented. It looks like I already had JSDocs for the prefix option in the constructor but the actual docs hadn't been published -- I've just re-uploaded them 👍.
