### ISSUE TITLE
'content' ignored in '::before' pseudo declarations

### ISSUE THREAD

**Issue by aronallen** [rtsao/styletron#70]
For some reason the 'content' property is ignored in '::before' pseudo element declarations.

**Comment by rtsao** [comment]
The content property needs to be wrapped in quotes in CSS, so in JS it needs to be "double-wrapped", e.g. `{content: '"foo"'}`. Maybe what you're experiencing could be due to this?

**Comment by aronallen** [comment]
@rtsao thanks for getting back, I tried your suggestion, it works like a charm.
