### ISSUE TITLE
The document of styletron-utils is missing

### ISSUE THREAD

**Issue by jas-chen** [rtsao/styletron#71]
Hi,
Can't find styletron-utils doc in http://styletron.js.org/ or README.md.

**Comment by faddee** [comment]
I think the idea is to use `injectDeclaration` rather than `insertRule`. But there is not way to use `injectStylePrefixed` through `injectDeclaration` which could be a bit problematic in some cases.

**Comment by rtsao** [comment]
`styletron-utils` doesn't exist anymore in V4.
