### ISSUE TITLE
Preact version

### ISSUE THREAD

**Issue by quentin-sommer** [rtsao/styletron#81]
Hi, 

Would styletron work with preact natively (without preat-compat) ?

**Comment by faddee** [comment]
Haven't tried but I guess not since `styletron-react` uses `React.createElement` instead of JSX.

**Comment by rtsao** [comment]
Yes, I don't think `styletron-react` doesn't do anything weird that would require preact-compat. https://twitter.com/_developit/status/817868067137081345

Just alias `react-dom` and `react` to `preact/aliases`

**Comment by quentin-sommer** [comment]
Thanks!
