### ISSUE TITLE
StyledElement.getBoundingClientRect() doesn't work. Any alternatives?

### ISSUE THREAD

**Issue by femesq** [rtsao/styletron#86]
I'm getting this exception:

```
Uncaught TypeError: StyledElement.getBoundingClientRect is not a function
```
when "iterating" on some elements to "find" the higher one.
Is there any way to reach this React's function on StyledElements?

Thanks,

**Comment by faddee** [comment]
`getBoundingClientRect` is a method on the DOM element. You need to reference to your element with `innerRef` to be able to do that.

```ts
const MyStyledElement = styled('div', {/* ... */});
<MyStyledElement innerRef={el => el.getBoundingClientRect()} />
```

**Comment by femesq** [comment]
Thanks @faddee, worked great for me, with some adjusts to my use-case..
