### ISSUE TITLE
Typescript definition styletron-react performance

### ISSUE THREAD

**Issue by crohlfs** [rtsao/styletron#99]
After using this package for around a week my Visual Studio Code hints and error checking has slowed considerably (sometimes up to 10 second delay on error or type information). I believe I've tracked it down to my use of styletron-react.

I think it's something to do with the way generics are used in the type definition, since when I run `tsc` with the `--diagnostics` flag, I have a huge number of types.

- ~400 types: `const Component2 = styled(Component1, {});`
- ~50 types: `const Component2 = styled('div', {});`
- ~1200 types `const Component2 = styled(Component1, ({ }) => ({}));`

Not sure if typescript version matters, but I've had the issue on 2.2 and 2.1. Also don't think .tsconfig matters since I got these numbers from a single file.

@faddee I see you did a lot of work on the typings, have you run into any similar issues?

In the meantime I've added a function in front of the `styled` function to strip any typing and my project is now fast again.

```typescript
(base: any, style: any) => styled(base, style) as any;
```

I'll keep investigating and see if I can get those numbers down.

**Comment by faddee** [comment]
I haven't noticed anything significant. But I'll have a look into it.

**Comment by seivan** [comment]
@crohlfs Can you explain more how you stripped any typing to increase linter speed? I didn't quite follow.

**Comment by crohlfs** [comment]
I made a styletron.ts file in my project which contains only the function given above, basically re-exporting styletron using 'any' instead of the proper generics provided by the typings.

I've been trying to find a real solution every now and then but it seems like something around React.CSSProperties (which has 250+ optional properties).

**Comment by faddee** [comment]
It seems to have nothing to do with `CSSProperties` it self. But when I used intersection type instead of extending an interface function, my type check time improved from ~5.5s to ~4s. So hopefully #120 will help you. Thank you for pointing me at the right direction.
